// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDSqkMrQ5TYKMG4nCJv86nsvX3BhIRHIh0',
    appId: '1:119634674159:web:636b216b571826cf29361a',
    messagingSenderId: '119634674159',
    projectId: 'openai-4b026',
    authDomain: 'openai-4b026.firebaseapp.com',
    storageBucket: 'openai-4b026.appspot.com',
    measurementId: 'G-DLFSTT5S58',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAgGp85LdrU0eqwYkoZ1SrQyNCufMheJF8',
    appId: '1:119634674159:android:d03af96484673f3729361a',
    messagingSenderId: '119634674159',
    projectId: 'openai-4b026',
    storageBucket: 'openai-4b026.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8X0p0EqYJynPqydq5SqnpDrftGmWxIHc',
    appId: '1:119634674159:ios:09b3d190eceb385a29361a',
    messagingSenderId: '119634674159',
    projectId: 'openai-4b026',
    storageBucket: 'openai-4b026.appspot.com',
    iosBundleId: 'com.example.userOtp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8X0p0EqYJynPqydq5SqnpDrftGmWxIHc',
    appId: '1:119634674159:ios:8b7d358437e941fc29361a',
    messagingSenderId: '119634674159',
    projectId: 'openai-4b026',
    storageBucket: 'openai-4b026.appspot.com',
    iosBundleId: 'com.example.userOtp.RunnerTests',
  );
}
